<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">

  <name>conveyor_interfaces</name>
  <version>0.0.0</version>

  <description>Custom interfaces for conveyor system</description>

  <maintainer email="VaibhavDeveloper@todo.todo">
    VaibhavDeveloper
  </maintainer>

  <license>TODO: License declaration</license>


  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS 2 interface generation -->
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- Runtime support for generated interfaces -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Mark this package as an interface package -->
  <member_of_group>rosidl_interface_packages</member_of_group>


  <!-- Testing -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>